PandaPoker/apps/profiles/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from profiles import views

urlpatterns = patterns('',
    #url(r"^$", direct_to_template, {"template": "about/about.html"}, name="what_next"),
    url(r'^$', views.IndexView.as_view(), name='index_profiles'),
)

PandaPoker/apps/stats/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from apps.stats import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index_stats'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^player/(?P<pk>\d+)/$', views.PlayerInfoView.as_view(), name='playerinfo'),
)

PandaPoker/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

#from pinax.apps.account.openid_consumer import PinaxConsumer

handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    }, name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^about/", include("about.urls")),
    url(r"^profiles/", include("profiles.urls", namespace="profiles")),
    url(r"^variations/", include("variations.urls", namespace="variations")),
    url(r"^stats/", include("stats.urls", namespace="stats")),
    url(r"^payouts/", include("payouts.urls", namespace="payouts")),
    #url(r"^openid/", include(PinaxConsumer().urls)),   
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

PandaPoker/apps/profiles/models.py
from django.db import models

# Create your models here.

PandaPoker/apps/profiles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.db.models import Count, Sum, Avg

#from account.models import Account
from django.contrib.auth.models import User
from apps.stats.models import Player, Game
import operator

class IndexView(generic.ListView):
    template_name = 'profiles.html'
    context_object_name = 'profiles_list'
    
    def get_queryset(self):
        full_players = []
        players = {}
        users = User.objects.order_by('first_name')
        players = Player.objects.order_by('player', '-highesthand').annotate(total_knockouts=Sum("knockouts"))
        
        for user in users:
            players = Player.objects.filter(player__exact = user.id).order_by('-highesthand').annotate(total_knockouts=Sum("knockouts"))
            if players:
                current = players[0]
                current.average_standing = 0
                current.all_knockouts = 0
                for player in players:
                    current.average_standing += player.standing
                    current.all_knockouts += player.knockouts
                current.games_played = len(players)
                current.average_standing = round(float(current.average_standing)/float(current.games_played), 3)
                current.username = user
		current.hand = str(player.highesthand).split(";")[0]
                full_players.append(current)
        full_players.sort(key=operator.attrgetter('average_standing'), reverse=False)
        return full_players

PandaPoker/apps/profiles/templates/profiles.html
{% extends "theme_base.html" %}
{% load url from future %}
{% load staticfiles %}

{% load i18n %}

{% block head_title %}{% trans "Profiles" %}{% endblock %}

{% block body %}
	{% if user.is_authenticated %}
    <div class="hero-unit">
    {% block banner %}
    	<img src="{{STATIC_URL}}main_logo.png" style="width:100px;" align="left" alt="logo" />
        <h1>&nbsp;Player Profiles</h1>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;How do you stack against your fellow poker players?</p>
    {% endblock %}
    </div>
    
		{% if profiles_list %}		
			
			<div class="row">
				{% for player in profiles_list %}
				<div class="span4">
					{% if player.has_name %}
					<h4><a href="{% url 'stats:playerinfo' player.id %}">{{player}}</a></h4>
					{% else %}
					<h4><a href="{% url 'stats:playerinfo' player.id %}">{{player.username}}</a></h4>
					{% endif %}
					<ul>
<!-- 						<img src="{{STATIC_URL}}logo.png" style="width:100px;" alt="logo" /> -->
<!-- 						&nbsp; -->
						<li><p><b>Games Played:</b> {{player.games_played}}</p></li>
						<li><p><b>Average Placing:</b> {{player.average_standing}}</p></li>
						<li><p><b>Highest Hand:</b> {{player.hand}}</p></li>
						<li><p><b>Knockouts:</b> {{player.all_knockouts}}</p></li>
					</ul>
				</div>
				{% endfor %}
			</div>
		{% else %}
			<p>No profiles are available.</p>			
		{% endif %}
	{% endif %}
{% endblock %}