PandaPoker/apps/payouts/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from apps.payouts import views

urlpatterns = patterns('',
    #url(r"^$", direct_to_template, {"template": "about/about.html"}, name="what_next"),
    url(r'^$', views.IndexView.as_view(), name='index_payouts'),
)

PandaPoker/apps/profiles/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from profiles import views

urlpatterns = patterns('',
    #url(r"^$", direct_to_template, {"template": "about/about.html"}, name="what_next"),
    url(r'^$', views.IndexView.as_view(), name='index_profiles'),
)

PandaPoker/apps/stats/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from apps.stats import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index_stats'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^player/(?P<pk>\d+)/$', views.PlayerInfoView.as_view(), name='playerinfo'),
)

PandaPoker/apps/variations/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from apps.variations import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index_variations'),
    #url(r'add/$', views.AddView.as_view(), name='add_variation'),
    #url(r'outline/$', views.outline, name='outline_variation'),
)

PandaPoker/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

#from pinax.apps.account.openid_consumer import PinaxConsumer

handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    }, name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^about/", include("about.urls")),
    url(r"^profiles/", include("profiles.urls", namespace="profiles")),
    url(r"^variations/", include("variations.urls", namespace="variations")),
    url(r"^stats/", include("stats.urls", namespace="stats")),
    url(r"^payouts/", include("payouts.urls", namespace="payouts")),
    #url(r"^openid/", include(PinaxConsumer().urls)),   
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

PandaPoker/templates/_footer.html
{% load i18n %}
<div class="legal">
    {% trans "&copy; 2014 Gvangerous &lt;Version 1.0&gt;" %}
</div>

PandaPoker/templates/banner_base.html
{% extends "site_base.html" %}
{% load url from future %}
{% load i18n %}

{% block body_base %}
	
    <div class="container">
        {% include "_messages.html" %}
        <div class="hero-unit">
        {% block banner %}
            <h1>Hello, world!</h1>
            <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
            <p><a class="btn primary large">Learn more &raquo;</a></p>
        {% endblock %}
        </div>
        {% if user.is_authenticated %}
        <div class="row">
            <div class="span4">
            {% block column-1 %}
				<h2>Variations</h2>
				<p>See the list of ever growing variations, or add your own.</p>
				<p><a class="btn" href="{% url 'variations:index_variations' %}">View details &raquo;</a></p>
			{% endblock %}
            </div>
            <div class="span4">
            {% block column-2 %}
				<h2>Profiles</h2>
				<p>Want to know what we think of each players ability and personality?</p>
				<p><a class="btn" href="{% url 'profiles:index_profiles' %}">View details &raquo;</a></p>
			{% endblock %}
            </div>
            <div class="span4">
            {% block column-3 %}
				<h2>Player Stats</h2>
				<p>View the standings of all the players throughout the year.</p>
				<p><a class="btn disabled" href="{% url 'stats:index_stats'  %}" value="disable">Coming Soon  &raquo;</a></p>
			{% endblock %}
            </div>
            <div class="span4">
            {% block column-4 %}
                <h2>Payouts</h2>
                <p>How the money should break down dependent on the number of players and cash.</p>
                <p><a class="btn" href="{% url 'payouts:index_payouts' %}">View details &raquo;</a></p>
            {% endblock %}
            </div>
        </div>
    	{% endif %}
    </div>
    
{% endblock %}

PandaPoker/templates/homepage.html
{% extends "banner_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
 	<img src="{{STATIC_URL}}black_logo.png" style="width:100px;" align="left" alt="logo" />
    <h1>{% trans "&nbsp;Panda Poker ... Test!" %}</h1>
     
    {% if user.is_authenticated %}
        {% url what_next as what_next_url %}
        <p>&nbsp;&nbsp;&nbsp;&nbsp;Welcome to the site where poker players are separated from gamblers.</p>
    {% else %}
        {% url acct_login as login_url %}
        {% ifsetting ACCOUNT_OPEN_SIGNUP %}
            {% url acct_signup as signup_url %}
            <p>{% blocktrans %}&nbsp;&nbsp;&nbsp;&nbsp;You can <a href="{{ login_url }}" class="btn">Log In</a> or <a href="{{ signup_url }}" class="btn primary">Sign Up</a>{% endblocktrans %}</p>
        {% else %}
            <p>{% blocktrans %}&nbsp;&nbsp;&nbsp;&nbsp;You can <a href="{{ login_url }}" class="btn primary large">Log In</a>{% endblocktrans %}</p>
        {% endifsetting %}
    {% endif %}
{% endblock %}

PandaPoker/templates/site_base.html
{% extends "theme_base.html" %}

{% load metron_tags %}
{% load i18n %}

{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}

{% block footer %}
<div class="legal">
    {% include "_footer.html" %}
</div>
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}